class Headers:
    location = 'Location'
    sex = 'Sex'
    age = 'Age'
    avg_mort = 'avg_mortality'
    avg_pop = 'avg_population'
    Interval = 'Interval'
    Mx = 'M_x'
    ax = 'a_x'
    qx = 'q_x'
    px = 'p_x'
    l_x = 'l(x)'
    d_x = 'dx'
    L_x = 'Lx'
    T_x = 'Tx'
    e_x = 'e(x)'
