class InfostatColumns:
    population = 'Population'
    year = 'Year'
    age = 'Age'
    sex = 'Sex'
    location = 'Location'
    region = 'Region'
    total = 'Total'
    male = 'Male'
    female = 'Female'
    avg_population = 'avg_population'
    mortality = 'Mortality'
    mean_mortality = 'Mean_Mortality'